"""Genera notebooks/train_ecg_classifier.ipynb (ejecutar una vez desde la raíz del repo)."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

NB = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "pygments_lexer": "ipython3"},
    },
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# Clasificación ECG — 4 clases (baseline MLP)\n",
                "\n",
                "Entrena un **perceptrón multicapa (MLP)** sobre las **12 derivaciones** alineadas y re-muestreadas a longitud fija.\n",
                "\n",
                "**Salida:** `artifacts/models/ecg_mlp_4class.joblib` (consumido por la app Streamlit).\n",
                "\n",
                "Clases (SNOMED CT vía `ConditionNames_SNOMED-CT.csv`):\n",
                "- Sinus Bradycardia · Sinus Rhythm · Atrial Fibrillation · Sinus Tachycardia\n",
                "\n",
                "La primera celda fija la raíz del repo y el **cwd** (así las rutas relativas del `.env` coinciden con Streamlit).\n",
                "\n",
                "**Jupyter:** abre el notebook desde la carpeta del proyecto, no desde `src/`. "
                "Si usas terminal: `cd` a la raíz y luego `jupyter notebook notebooks/train_ecg_classifier.ipynb`.\n",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import os\n",
                "import sys\n",
                "from pathlib import Path\n",
                "\n",
                "ROOT = Path.cwd().resolve()\n",
                "if not (ROOT / \"src\").is_dir():\n",
                "    ROOT = ROOT.parent\n",
                "if not (ROOT / \"src\").is_dir():\n",
                "    raise FileNotFoundError(\n",
                "        \"No se encontró la carpeta src/. Abre el notebook desde la raíz del proyecto (carpeta que contiene src/ y notebooks/).\"\n",
                "    )\n",
                "os.chdir(ROOT)\n",
                "sys.path.insert(0, str(ROOT))\n",
                "print(\"ROOT =\", ROOT)\n",
                "print(\"cwd  =\", Path.cwd())\n",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import random\n",
                "from collections import defaultdict\n",
                "\n",
                "import joblib\n",
                "import numpy as np\n",
                "from sklearn.metrics import classification_report\n",
                "from sklearn.model_selection import train_test_split\n",
                "from sklearn.neural_network import MLPClassifier\n",
                "from sklearn.preprocessing import StandardScaler\n",
                "\n",
                "from src.config.settings import get_settings\n",
                "from src.data.metadata import discover_record_refs\n",
                "from src.data.parsers import header_to_metadata\n",
                "from src.modeling.label_mapping import pick_primary_class\n",
                "from src.modeling.train_utils import features_for_mlp, load_12lead_aligned\n",
                "\n",
                "random.seed(42)\n",
                "np.random.seed(42)\n",
                "\n",
                "settings = get_settings()\n",
                "TARGET_LEN = 5000  # 10 s @ 500 Hz — coherente con el dataset\n",
                "MAX_PER_CLASS = 150  # subconjunto manejable; subir con más RAM/tiempo\n",
                "MAX_SCAN = 8000  # máximo de .hea a inspeccionar\n",
                "\n",
                "refs = discover_record_refs(settings, limit=MAX_SCAN)\n",
                "print(\"WFDB (config):\", settings.wfdb_records_dir)\n",
                "print(\"¿Existe carpeta?\", settings.wfdb_records_dir.is_dir())\n",
                "print(\"Registros .hea encontrados (muestra):\", len(refs))\n",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "X_list = []\n",
                "y_list = []\n",
                "counts = defaultdict(int)\n",
                "\n",
                "for ref in refs:\n",
                "    meta = header_to_metadata(ref)\n",
                "    label = pick_primary_class(meta.get(\"snomed_ct_codes\", []))\n",
                "    if label is None:\n",
                "        continue\n",
                "    if counts[label] >= MAX_PER_CLASS:\n",
                "        continue\n",
                "    try:\n",
                "        aligned, fs, _ = load_12lead_aligned(settings, ref)\n",
                "        xrow = features_for_mlp(aligned, fs, TARGET_LEN)\n",
                "        X_list.append(xrow.ravel())\n",
                "        y_list.append(label)\n",
                "        counts[label] += 1\n",
                "    except Exception:\n",
                "        continue\n",
                "\n",
                "print(\"Por clase:\", dict(counts))\n",
                "print(\"Total:\", len(y_list))\n",
                "if len(y_list) < 40:\n",
                "    raise RuntimeError(\n",
                "        f\"Muy pocas muestras ({len(y_list)}). Dataset esperado en: {settings.wfdb_records_dir} \"\n",
                "        f\"(existe={settings.wfdb_records_dir.is_dir()}). Copia WFDBRecords bajo data/raw/ o revisa WFDB_RECORDS_DIR en .env.\"\n",
                "    )\n",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "X = np.stack(X_list, axis=0)\n",
                "y = np.array(y_list)\n",
                "classes = sorted(np.unique(y))\n",
                "print(\"Clases:\", classes)\n",
                "\n",
                "X_train, X_test, y_train, y_test = train_test_split(\n",
                "    X, y, test_size=0.25, random_state=42, stratify=y\n",
                ")\n",
                "scaler = StandardScaler()\n",
                "X_train_s = scaler.fit_transform(X_train)\n",
                "X_test_s = scaler.transform(X_test)\n",
                "\n",
                "clf = MLPClassifier(\n",
                "    hidden_layer_sizes=(128, 64),\n",
                "    max_iter=120,\n",
                "    random_state=42,\n",
                "    early_stopping=True,\n",
                "    validation_fraction=0.1,\n",
                ")\n",
                "clf.fit(X_train_s, y_train)\n",
                "y_pred = clf.predict(X_test_s)\n",
                "print(classification_report(y_test, y_pred, zero_division=0))\n",
                "class_names_out = list(clf.classes_)\n",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "out_dir = ROOT / \"artifacts\" / \"models\"\n",
                "out_dir.mkdir(parents=True, exist_ok=True)\n",
                "out_path = out_dir / \"ecg_mlp_4class.joblib\"\n",
                "\n",
                "bundle = {\n",
                "    \"model\": clf,\n",
                "    \"scaler\": scaler,\n",
                "    \"class_names\": class_names_out,\n",
                "    \"target_len\": TARGET_LEN,\n",
                "    \"n_features\": X.shape[1],\n",
                "}\n",
                "joblib.dump(bundle, out_path)\n",
                "print(\"Guardado:\", out_path.resolve())\n",
            ],
        },
    ],
}


def main() -> None:
    path = ROOT / "notebooks" / "train_ecg_classifier.ipynb"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(NB, indent=1, ensure_ascii=False), encoding="utf-8")
    print("Wrote", path)


if __name__ == "__main__":
    main()
